baseurl = "https://tju-yxq.github.io/"
title = "小段子的技术博客"
theme = "hugo-theme-cleanwhite"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
preserveTaxonomyNames = true
hasCJKLanguage = true

[languages]
  [languages.zh]
    weight = 1
    languageCode = "zh-CN"
    title = "小段子的技术博客"
  [languages.en]
    weight = 2
    languageCode = "en-US"
    title = "Xiao Duanzi's Tech Blog"

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "小段子的技术博客"
  description = "小段子，天大智算在读本科生 | 这里是小段子的博客，与你一起发现更大的世界。"
  keyword = "小段子，网安"
  slogan = "流水不争先，争的是涓涓细流"
  upstreamAttribution = false

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = true
  leancloud_app_id = "SGnXibnQUAvlDjZEiN4zXw6n-MdYXbMMI"
  leancloud_app_key = "Nn1F9pN6lBgHmcRjwgaD4A0g"

  # algolia site search
  algolia_search = true
  algolia_appId = "5ZQ7C4AZHX"
  algolia_indexName = "My blog"
  algolia_apiKey = "d525505f2d6b5177054e412fc11d53ee"

  # Sidebar settings
  sidebar_about_description = "天大智算24级网安本科在读，爱运动，爱学习，羽毛球乒乓球篮球足球台球麻将桌游剧本杀等等都是爱好嘿嘿"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/yxq.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = true
  artalk_server = "https://xxx.xxx.com"
  artalk_site = "xxx blog"

  # AI Chatbot settings
  ai_chat_enable = true
  ai_chat_api_url = "http://localhost:8000"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/custom-table-math.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "3023209091@tju.edu.cn"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/tju-yxq"
  wechat         = "img/wechat.jpg"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "小卷毛的博客"
  href =  "http://www.never-ending.info/"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  #[[params.additional_menus]]
  #title =  "NOTES"
  #href =  "/notes/"
  [[params.additional_menus]]
  title =  "关于"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']

[params.giscus]
  data_repo="tju-yxq/yxq-blog-source"
  data_repo_id="R_kgDOP0dLgw"
  data_category="Comments"
  data_category_id="DIC_kwDOP0dLg84CvygP"
  data_mapping="pathname"
  data_strict="0"
  data_reactions_enabled="1"
  data_emit_metadata="0"
  data_input_position="top"
  data_theme="light_high_contrast"
  data_lang="zh-CN"
  data_loading="lazy"
  crossorigin="anonymous"
